server:
  port: 8888

spring:
  application:
    name: CONFIG_SERVER
  cloud:
    #Config server settings
    config:
      server:
        git:
          uri: https://github.com/Yaroslav1395/psup-config-repo.git
          default-label: develop
          clone-on-start: true
          search-paths:
            - '{application}'
      enabled: false

#Loging config
#If !local = INFO
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG

#Security config. Should be env property
#To env
config:
  server:
    username: myUsername
    password: mySecretPassword
encrypt:
  key: mySuperSecretKey
